image_types_nfi.bbclass: Fix do_image_complete
For dm800(se) and dm500hd.

ERROR: openvision-enigma2-image-1.0-r0 do_image_complete: The recipe openvision-enigma2-image is trying to install
files into a shared area when those files already exist. Those files and their manifest location are:
/home/hains/openvision-development-platform/build/tmp/deploy/images/dm500hd/openvision-enigma2-develop-9.1-r3-dm500hd.rootfs.jffs2
(not matched to any task)
Please verify which recipe should provide the above files.

Introduced with commit:
https://github.com/openembedded/openembedded-core/commit/05f6042a40bb772f7ce8d6819c5b2937d8c9808d

Use DEPLOY_DIR_IMAGE as much as possible since with IMGDEPLOYDIR the image will become a little bit bigger.